// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: gogate.proto

package gogate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests  *GateRequest   `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Responses *GateResponse  `protobuf:"bytes,2,opt,name=responses,proto3" json:"responses,omitempty"`
	Handshake *GateHandshake `protobuf:"bytes,3,opt,name=handshake,proto3" json:"handshake,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_gogate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_gogate_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetRequests() *GateRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *Packet) GetResponses() *GateResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *Packet) GetHandshake() *GateHandshake {
	if x != nil {
		return x.Handshake
	}
	return nil
}

type GateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string        `protobuf:"bytes,10,opt,name=method,proto3" json:"method,omitempty"`
	Url           string        `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Host          string        `protobuf:"bytes,12,opt,name=host,proto3" json:"host,omitempty"`
	Header        []*GateHeader `protobuf:"bytes,13,rep,name=header,proto3" json:"header,omitempty"`
	Body          []byte        `protobuf:"bytes,14,opt,name=body,proto3" json:"body,omitempty"`
	ContentLength int64         `protobuf:"varint,15,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	RemoteAddr    string        `protobuf:"bytes,16,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
}

func (x *GateRequest) Reset() {
	*x = GateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateRequest) ProtoMessage() {}

func (x *GateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateRequest.ProtoReflect.Descriptor instead.
func (*GateRequest) Descriptor() ([]byte, []int) {
	return file_gogate_proto_rawDescGZIP(), []int{1}
}

func (x *GateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GateRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GateRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GateRequest) GetHeader() []*GateHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GateRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GateRequest) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *GateRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type GateHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *GateHeader) Reset() {
	*x = GateHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateHeader) ProtoMessage() {}

func (x *GateHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gogate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateHeader.ProtoReflect.Descriptor instead.
func (*GateHeader) Descriptor() ([]byte, []int) {
	return file_gogate_proto_rawDescGZIP(), []int{2}
}

func (x *GateHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GateHeader) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type GateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StatusCode    int32         `protobuf:"varint,10,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Header        []*GateHeader `protobuf:"bytes,13,rep,name=header,proto3" json:"header,omitempty"`
	Body          []byte        `protobuf:"bytes,14,opt,name=body,proto3" json:"body,omitempty"`
	ContentLength int64         `protobuf:"varint,15,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
}

func (x *GateResponse) Reset() {
	*x = GateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateResponse) ProtoMessage() {}

func (x *GateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateResponse.ProtoReflect.Descriptor instead.
func (*GateResponse) Descriptor() ([]byte, []int) {
	return file_gogate_proto_rawDescGZIP(), []int{3}
}

func (x *GateResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GateResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GateResponse) GetHeader() []*GateHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GateResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GateResponse) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type GateHandshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service   string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	WatchOnly bool   `protobuf:"varint,2,opt,name=watch_only,json=watchOnly,proto3" json:"watch_only,omitempty"`
}

func (x *GateHandshake) Reset() {
	*x = GateHandshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateHandshake) ProtoMessage() {}

func (x *GateHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_gogate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateHandshake.ProtoReflect.Descriptor instead.
func (*GateHandshake) Descriptor() ([]byte, []int) {
	return file_gogate_proto_rawDescGZIP(), []int{4}
}

func (x *GateHandshake) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GateHandshake) GetWatchOnly() bool {
	if x != nil {
		return x.WatchOnly
	}
	return false
}

var File_gogate_proto protoreflect.FileDescriptor

var file_gogate_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x6f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x78, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x74,
	0x65, 0x22, 0xc3, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x3a, 0x0a, 0x08,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x78, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x67, 0x6f, 0x67, 0x61,
	0x74, 0x65, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x3d, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x78, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x74, 0x65, 0x2e,
	0x47, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x61, 0x78, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x47,
	0x61, 0x74, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x09, 0x68, 0x61,
	0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x22, 0xee, 0x01, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x78, 0x67, 0x72,
	0x69, 0x64, 0x2e, 0x67, 0x6f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x22, 0x36, 0x0a, 0x0a, 0x47, 0x61, 0x74, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0xb1, 0x01, 0x0a, 0x0c, 0x47, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x78, 0x67, 0x72, 0x69, 0x64, 0x2e,
	0x67, 0x6f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x22, 0x48, 0x0a, 0x0d, 0x47, 0x61, 0x74, 0x65, 0x48, 0x61, 0x6e, 0x64,
	0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x77, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x77, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x6e, 0x6c, 0x79, 0x42, 0x2d,
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x78, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x67, 0x6f, 0x67,
	0x61, 0x74, 0x65, 0x50, 0x01, 0xaa, 0x02, 0x15, 0x41, 0x78, 0x47, 0x72, 0x69, 0x64, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gogate_proto_rawDescOnce sync.Once
	file_gogate_proto_rawDescData = file_gogate_proto_rawDesc
)

func file_gogate_proto_rawDescGZIP() []byte {
	file_gogate_proto_rawDescOnce.Do(func() {
		file_gogate_proto_rawDescData = protoimpl.X.CompressGZIP(file_gogate_proto_rawDescData)
	})
	return file_gogate_proto_rawDescData
}

var file_gogate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gogate_proto_goTypes = []interface{}{
	(*Packet)(nil),        // 0: com.axgrid.gogate.Packet
	(*GateRequest)(nil),   // 1: com.axgrid.gogate.GateRequest
	(*GateHeader)(nil),    // 2: com.axgrid.gogate.GateHeader
	(*GateResponse)(nil),  // 3: com.axgrid.gogate.GateResponse
	(*GateHandshake)(nil), // 4: com.axgrid.gogate.GateHandshake
}
var file_gogate_proto_depIdxs = []int32{
	1, // 0: com.axgrid.gogate.Packet.requests:type_name -> com.axgrid.gogate.GateRequest
	3, // 1: com.axgrid.gogate.Packet.responses:type_name -> com.axgrid.gogate.GateResponse
	4, // 2: com.axgrid.gogate.Packet.handshake:type_name -> com.axgrid.gogate.GateHandshake
	2, // 3: com.axgrid.gogate.GateRequest.header:type_name -> com.axgrid.gogate.GateHeader
	2, // 4: com.axgrid.gogate.GateResponse.header:type_name -> com.axgrid.gogate.GateHeader
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gogate_proto_init() }
func file_gogate_proto_init() {
	if File_gogate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gogate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateHandshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gogate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gogate_proto_goTypes,
		DependencyIndexes: file_gogate_proto_depIdxs,
		MessageInfos:      file_gogate_proto_msgTypes,
	}.Build()
	File_gogate_proto = out.File
	file_gogate_proto_rawDesc = nil
	file_gogate_proto_goTypes = nil
	file_gogate_proto_depIdxs = nil
}
